integrations:
  rescuetime:
    frequency: "daily"
    overview: true
    top-categories: true
    top-activities: true
  # last-fm:
  #  frequency: "daily"
  #  all: true
  #pocket-casts:
  #  frequency: "daily"
  #  all: true
  oura-ring:
    frequency: "daily"
    all: true
  # clockify:
  # spotify:
  # goodreads:
